#!/bin/bash

readonly SCRIPT_DIR="$(dirname "$(realpath -s "${BASH_SOURCE[0]}")")"

if (( "$#" == 0 )); then
  test_files=("${SCRIPT_DIR}"/*.bats)
else
  test_files=("$@")
fi
"${SCRIPT_DIR}/libs/bats-core/bin/bats" "${test_files[@]}"

