#!/bin/bash

UNRESOLVED_DIR="$(dirname "${BASH_SOURCE[0]}")" || exit "$?"
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
readonly SCRIPT_DIR

if (( "$#" == 0 )); then
  test_files=("${SCRIPT_DIR}"/*.bats)
else
  test_files=("$@")
fi
"${SCRIPT_DIR}/libs/bats-core/bin/bats" "${test_files[@]}"

