#!/bin/bash

readonly SCRIPT_DIR="$(dirname "$(realpath -s "${BASH_SOURCE[0]}")")"

grep --recursive --word-regexp --files-with-matches  \
  --exclude-dir="${SCRIPT_DIR}/../test/libs" \
  --exclude=*.swp \
  "${SCRIPT_DIR}/.." \
  --regexp='#!/bin/bash' \
  --regexp='#!/usr/bin/env bats' \
  | entr "${SCRIPT_DIR}/run-tests"

