#!/bin/bash

if [[ ! -d dotfiles ]]; then
  git clone https://github.com/adyang/dotfiles.git || exit "$?"
fi

cd dotfiles \
  && printf '%s\n' "export DOT_DIR='${PWD}'" > "${HOME}/.dot-env" \
  && ./generate-ssh-keys \
  && ./install

