#!/bin/bash

UNRESOLVED_DIR="$(dirname "${BASH_SOURCE[0]}")" || exit "$?"
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
readonly SCRIPT_DIR

# shellcheck source=lib/log.sh
source "${SCRIPT_DIR}/lib/log.sh"

main() {
  header 'Configure MacOS'
  prepare_macos_configuration || exit "$?"
  configure_iterm2 || exit "$?"
  configure_dock || exit "$?"
  configure_finder || exit "$?"
  configure_spotlight || exit "$?"
  configure_spectacle || exit "$?"
  harden_macos || exit "$?"
  disable_siri || exit "$?"
  reload_preferences || exit "$?"
}

prepare_macos_configuration() {
  sub_header 'Prepare MacOS Configuration'
  osascript -e 'tell application "System Preferences" to quit'
}

configure_iterm2() {
  sub_header 'Configure iterm2 Preferences'
  # shellcheck disable=SC2088
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string '~/.iterm2' &&
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

configure_dock() {
  sub_header 'Configure MacOS Dock'
  defaults write com.apple.dock persistent-apps -array &&
  killall Dock
}

configure_finder() {
  sub_header 'Configure MacOS Finder'
  defaults write com.apple.finder NewWindowTarget -string 'PfLo' &&
  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}" &&

  defaults write com.apple.finder ShowMountedServersOnDesktop -bool true &&

  defaults write com.apple.finder AppleShowAllFiles -bool true &&
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true &&
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false &&

  defaults write com.apple.finder _FXShowPosixPathInTitle -bool true &&
  defaults write com.apple.finder FXPreferredViewStyle -string 'Nlsv' &&

  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true &&
  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true &&

  killall Finder
}

configure_spotlight() {
  sub_header 'Configure Spotlight'
  defaults write com.apple.spotlight orderedItems -array \
    '{"enabled" = 1; "name" = "APPLICATIONS";}' \
    '{"enabled" = 1; "name" = "SYSTEM_PREFS";}' \
    '{"enabled" = 1; "name" = "DIRECTORIES";}' \
    '{"enabled" = 0; "name" = "MENU_SPOTLIGHT_SUGGESTIONS";}' \
    '{"enabled" = 0; "name" = "MENU_CONVERSION";}' \
    '{"enabled" = 0; "name" = "MENU_EXPRESSION";}' \
    '{"enabled" = 0; "name" = "MENU_DEFINITION";}' \
    '{"enabled" = 0; "name" = "MENU_OTHER";}' \
    '{"enabled" = 0; "name" = "DOCUMENTS";}' \
    '{"enabled" = 0; "name" = "PRESENTATIONS";}' \
    '{"enabled" = 0; "name" = "SPREADSHEETS";}' \
    '{"enabled" = 0; "name" = "PDF";}' \
    '{"enabled" = 0; "name" = "FONTS";}' \
    '{"enabled" = 0; "name" = "MESSAGES";}' \
    '{"enabled" = 0; "name" = "CONTACT";}' \
    '{"enabled" = 0; "name" = "EVENT_TODO";}' \
    '{"enabled" = 0; "name" = "IMAGES";}' \
    '{"enabled" = 0; "name" = "BOOKMARKS";}' \
    '{"enabled" = 0; "name" = "MUSIC";}' \
    '{"enabled" = 0; "name" = "MOVIES";}' &&
  defaults write com.apple.lookup.shared LookupSuggestionsDisabled -int 1 &&

  sudo killall mds &&
  sudo mdutil -i on / &&
  sudo mdutil -E /
}

configure_spectacle() {
  sub_header 'Configure Spectacle'
  osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Spectacle.app", hidden:false}' >/dev/null &&
  printf 'Existing login items:\n' &&
  osascript -e 'tell application "System Events" to get the name of every login item'
}

harden_macos() {
  sub_header 'Harden MacOS'
  sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1 &&
  sudo defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -int 0 &&
  defaults write '/Library/Application Support/CrashReporter/DiagnosticMessagesHistory' AutoSubmit -int 0
}

disable_siri() {
  sub_header 'Disable Siri'
  defaults write com.apple.Siri StatusMenuVisible -bool false &&
  defaults write com.apple.Siri UserHasDeclinedEnable -bool true &&
  defaults write com.apple.assistant.support 'Assistant Enabled' -int 0
}

reload_preferences() {
  sub_header 'Reload Preferences'
  killall -HUP cfprefsd &&
  killall SystemUIServer
}

(return 0 2>/dev/null) || main "$@"
