#!/bin/bash

UNRESOLVED_DIR="$(dirname "${BASH_SOURCE[0]}")" || exit "$?"
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
readonly SCRIPT_DIR

# shellcheck source=lib/log.sh
source "${SCRIPT_DIR}/lib/log.sh"

main() {
  DOT_HOME="${DOT_HOME:-${HOME}}"
  readonly DOT_HOME

  configure_vim
}

configure_vim() {
  header 'Configure Vim'
  local plugins=(
    'https://github.com/chriskempson/base16-vim.git'
    'https://github.com/scrooloose/nerdtree.git'
    'https://github.com/tpope/vim-fireplace.git'
    'https://github.com/pangloss/vim-javascript.git'
    'https://github.com/bhurlow/vim-parinfer.git'
    'https://github.com/tpope/vim-repeat.git'
    'https://github.com/tpope/vim-surround.git'
    'https://github.com/dense-analysis/ale.git'
  )
  install_vim_plugins "${plugins[@]}"
}

install_vim_plugins() {
  local plugins=("$@")
  local plugins_path="${DOT_HOME}/.vim/pack/plugins"
  mkdir -p "${plugins_path}"/{start,opt}
  for plugin in "${plugins[@]}"; do
    local basename="${plugin##*/}"
    local dirname="${basename%.*}"
    local plugin_dir="${plugins_path}/start/${dirname}"
    if [[ -d "${plugin_dir}" ]]; then
      git -C "${plugin_dir}" pull origin master || exit "$?"
    else
      git clone "${plugin}" "${plugin_dir}" || exit "$?"
    fi
  done
  vim -c 'helptags ALL' -c 'qall!' &> /dev/null
}

(return 0 2>/dev/null) || main "$@"
