#!/bin/bash

UNRESOLVED_DIR="$(dirname "${BASH_SOURCE[0]}")" || exit "$?"
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
readonly SCRIPT_DIR

# shellcheck source=lib/log.sh
source "${SCRIPT_DIR}/lib/log.sh"

main() {
  DOT_HOME="${DOT_HOME:-${HOME}}"
  readonly DOT_HOME

  header 'Configure Vim'
  configure_vim "${DOT_HOME}/.vim-plugins"
}

configure_vim() {
  local plugins_file="$1"
  local plugins=()
  local plugin
  while read -r plugin || [[ -n "${plugin}" ]]; do
    plugins+=("${plugin}")
  done <"${plugins_file}" || return "$?"

  install_vim_plugins "${plugins[@]}"
}

install_vim_plugins() {
  local plugins=("$@")
  local plugins_path="${DOT_HOME}/.vim/pack/plugins"
  mkdir -p "${plugins_path}"/{start,opt}
  for plugin in "${plugins[@]}"; do
    local basename="${plugin##*/}"
    local dirname="${basename%.*}"
    local plugin_dir="${plugins_path}/start/${dirname}"
    if [[ -d "${plugin_dir}" ]]; then
      git -C "${plugin_dir}" pull origin master || return "$?"
    else
      git clone "${plugin}" "${plugin_dir}" || return "$?"
    fi
  done
  vim -c 'helptags ALL' -c 'qall!' &> /dev/null
}

(return 0 2>/dev/null) || main "$@"
