#!/bin/bash

UNRESOLVED_DIR="$(dirname "${BASH_SOURCE[0]}")" || exit "$?"
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
GEN_SSH_HOME="${GEN_SSH_HOME:-${HOME}}"
readonly SCRIPT_DIR GEN_SSH_HOME

# shellcheck source=lib/log.sh
source "${SCRIPT_DIR}/lib/log.sh"

header 'Generate SSH Keys'
set +o allexport
unset -v passphrase
IFS= read -rsp 'Please enter desired passphrase for SSH key generation: ' passphrase || exit "$?"
if [[ -z "${passphrase}" ]]; then
  echo 'Error: passphrase should not be empty.'
  exit 1
fi

ssh-keygen -t ed25519 -f "${GEN_SSH_HOME}/.ssh/id_ed25519" -N "${passphrase}" || exit "$?"

expect <<EOF || exit "$?"
spawn ssh-add -K "${GEN_SSH_HOME}/.ssh/id_ed25519"
expect {
    -re "^Enter passphrase .*: $" { send -- "${passphrase}\r"; exp_continue }
    -re "Bad passphrase.*: $" { exit 1 }
    eof
}
EOF

pbcopy < "${GEN_SSH_HOME}/.ssh/id_ed25519.pub"
note 'Public key has been copied to the clipboard.'

