#!/usr/bin/env bash

readonly SCRIPTS_LIB_DIR="${CHEZMOI_WORKING_TREE}/lib"
readonly LOCAL_BIN_DIR="${HOME}/.local/bin"

# shellcheck source=../../lib/log.bash
source "${SCRIPTS_LIB_DIR}/log.bash"

main() {
  [[ "${CI}" == 'true' ]] || sudo_keep_alive
  configure_shell
  "${LOCAL_BIN_DIR}/dot-brew" || exit
  "${LOCAL_BIN_DIR}/dot-vim" || exit
  "${LOCAL_BIN_DIR}/dot-firefox" || exit
  "${LOCAL_BIN_DIR}/dot-asdf" || exit
  [[ "${CI}" == 'true' ]] || "${LOCAL_BIN_DIR}/dot-macos" || exit
}

sudo_keep_alive() {
  sudo --stdin --validate --prompt="Please enter %u's password for sudo: " || exit
  sudo_until_process_ends
}

sudo_until_process_ends() {
  while true; do
    sudo --non-interactive true
    sleep 20
    kill -0 "$$" || exit
  done 2>/dev/null &
}

configure_shell() {
  header "Configure Shell"
  sudo chsh -s /bin/zsh "$(whoami)" || exit
}

(return 0 2>/dev/null) || main "$@"
