---
name: dotfiles
on: [push]
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install bats-core dependencies for running tests
        run: brew install coreutils
      - name: Unit tests
        run: ./test/run-tests
      - name: Clean binaries and uninstall Homebrew to simulate clean bootstrap
        run: >
          rm -rv /usr/local/bin/{dotnet,R,Rscript,aws,aws_completer,aws_legacy_completer} /Applications/Firefox.app
          && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
      - name: Bootstrap dotfiles
        run: bash <(curl --fail --silent --show-error --location https://raw.githubusercontent.com/adyang/dotfiles/master/bootstrap) <<< $'ssh-key-pass\nsudo-pass\n\n'
