---
name: dotfiles
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install bats-core dependencies for running tests
        run: brew install coreutils
      - name: Unit tests
        run: ./test/run-tests
      - name: Clean binaries and uninstall Homebrew to simulate clean bootstrap
        run: >
          rm -rfv /usr/local/bin/{dotnet,R,Rscript,aws,aws_completer} '/Applications/Firefox.app' '/Applications/Google Chrome.app'
          && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
      - name: Bootstrap dotfiles
        run: bash <(curl --fail --silent --show-error --location https://raw.githubusercontent.com/adyang/dotfiles/master/bootstrap) <<< $'ssh-key-pass\nsudo-pass\n\n'
