---
name: dotfiles
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean binaries and uninstall Homebrew to simulate clean bootstrap
        run: >
          rm -rfv /usr/local/bin/{dotnet,R,Rscript,aws,aws_completer,2to3*,idle3*,pydoc3*,python3*,python3-config*} '/Applications/Firefox.app' '/Applications/Google Chrome.app'
          && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
      - name: Bootstrap dotfiles
        run: >
          unset HOMEBREW_NO_INSTALL_FROM_API
          && ./bootstrap <<<$'sudo-pass\n\no\n'
